# Generated by Django 3.2.9 on 2021-11-05 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_frequency', models.IntegerField(default=2, help_text='Frequency in minutes at which alert will be triggered')),
                ('product_search_phrase', models.CharField(help_text='Search term for which user wants product results', max_length=50)),
                ('website', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAlertResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(help_text='Response received from the server')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_alert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alerts.productalert')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAlerts',
        ),
    ]
